on:
  workflow_dispatch:
    inputs:
      name:
        description: 'name'
        required: true
        default: 'sample'
        type: string

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Happy New Year Action
        env:
          sample_secret: ${{ secrets.HappyNewYear }}
        run: |
          echo $sample_secret ${{ inputs.name }}